name = "Ice Cold"
author = "Haskeller"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "279fae5077d3eb43a6b20dc623a1ea9777f375a4823e9170dfc9c2b94804d7f3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4"]
