name = "New Beginnings"
author = "Haskeller"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "198dec70e3b602ef56f94f01d65ac726859bc51c24e1d7bf172b901b33336e08"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4"]
