name = "Ice Cold"
author = "Haskeller"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c7e3fcb6d87ef0663afcd500d191e09487dabe24e1bc9284dac2189cef6c369"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4"]
